INSERT INTO USER (id, user_id, password, name, email, post_time) VALUES (1, 'javajigi', 'test', '자바지기', 'javajigi@slipp.net', CURRENT_TIMESTAMP());
INSERT INTO USER (id, user_id, password, name, email, post_time) VALUES (2, 'yeon', '1234', '나연', 'yeon@slipp.net', CURRENT_TIMESTAMP());

INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (1, 2, 'post1', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (2, 2, 'post2', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (3, 2, 'post3', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (4, 2, 'post4', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (5, 2, 'post5', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (6, 2, 'post6', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (7, 2, 'post7', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (8, 2, 'post8', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (9, 2, 'post9', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (10, 2, 'post10', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (11, 2, 'post11', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (12, 2, 'post12', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (13, 2, 'post13', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (14, 2, 'post14', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (15, 2, 'post15', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (16, 2, 'post16', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (17, 2, 'post17', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (18, 2, 'post18', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (19, 2, 'post19', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (20, 2, 'post20', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (21, 2, 'post21', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (22, 2, 'post22', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (23, 2, 'post23', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (24, 2, 'post24', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (25, 2, 'post19', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (26, 2, 'post20', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (27, 2, 'post21', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (28, 2, 'post22', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (id, writer_id , title, contents, count_of_answer, deleted, post_time, updated_post_time) VALUES (29, 2, 'post23', 'post1', 0, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
